In [3]:
import pandas as pd
from pathlib import Path
from IPython.display import display

# Load WhatsApp chat exports
Reads all .txt files from the data/raw folder and loads them into a pandas DataFrame with columns: filename, path, text, and lines.

In [42]:
from pathlib import Path
from IPython.display import display

data_dir = Path('..') / 'data' / 'raw'
files = sorted(data_dir.glob('*.txt'))
rows = []

for p in files:
    try:
        text = p.read_text(encoding='utf-8')
    except UnicodeDecodeError:
        text = p.read_text(encoding='latin-1')
    lines = text.splitlines()
    rows.extend(lines[1:])

df_chats = pd.DataFrame({'text': rows})
print(f'Loaded {len(df_chats)} lines from {len(files)} chat files in {data_dir.resolve()}')
display(df_chats.head())

Loaded 48922 lines from 18 chat files in C:\Users\arsal\Desktop\second-voice\data\raw

                                                text
0  4/11/25, 2:40 AM - +92 318 0067351: aoa yaar m...
1        4/11/25, 2:40 AM - +92 318 0067351: yaad se
2  4/11/25, 8:03 AM - ~Arsalan Qasim: Sahi hy.. M...
3             4/11/25, 8:04 AM - +92 318 0067351: Ok
4  4/11/25, 8:04 AM - +92 318 0067351: M 8 30.pr ...

In [ ]:
import re

# Remove leading WhatsApp timestamp prefixes like "4/11/25, 2:40\u202fAM - "
timestamp_pattern = r'^\d{1,2}/\d{1,2}/\d{2},\s*\d{1,2}:\d{2}\s*(?:AM|PM|am|pm|\u202fAM|\u202fPM)?\s*-\s*'
df_chats['text'] = df_chats['text'].astype(str).str.replace(timestamp_pattern, '', regex=True)

# Extract sender names like "~Arsalan Qasim:" or "+92 318 0067351:" into a Person column
person_pattern = r'^\s*(?:~)?([^:]+?):\s*'
df_chats['Person'] = df_chats['text'].str.extract(person_pattern, expand=False).str.strip()
df_chats['text'] = df_chats['text'].str.replace(person_pattern, '', regex=True)

display(df_chats.head())

Stripped timestamps, extracted Person, and cleaned message text.

                                                text           Person
0  aoa yaar main na tumhare sath DE repeat kr rha...  +92 318 0067351
1                                            yaad se  +92 318 0067351
2  Sahi hy.. Main university pounch kar tum sy ly...    Arsalan Qasim
3                                                 Ok  +92 318 0067351
4  M 8 30.pr niklu ga yha se agr tune phle Jana h...  +92 318 0067351

In [40]:
df_chats.head(3)

                                                text           Person
0  aoa yaar main na tumhare sath DE repeat kr rha...  +92 318 0067351
1                                            yaad se  +92 318 0067351
2  Sahi hy.. Main university pounch kar tum sy ly...    Arsalan Qasim